### ISSUE TITLE
Deprecate enum automatic registering

### ISSUE THREAD

**Issue by yann-eugone** [yann-eugone/enum-bundle#17]
This feature is not really used, and Symfony did the [magic in `3.3`](https://symfony.com/doc/current/service_container/3.3-di-changes.html).

We should deprecate it.

- [x] Deprecate [ConventionedEnumCollectorCompilerPass](https://github.com/yokai-php/enum-bundle/blob/master/DependencyInjection/CompilerPass/ConventionedEnumCollectorCompilerPass.php) and remove all usages
- [x] Deprecate [DeclarativeEnumCollectorCompilerPass](https://github.com/yokai-php/enum-bundle/blob/master/DependencyInjection/CompilerPass/DeclarativeEnumCollectorCompilerPass.php)
- [x] Deprecate [bundle configuration](https://github.com/yokai-php/enum-bundle/blob/master/DependencyInjection/Configuration.php)
- [x] Add a note for next major

**Comment by yann-eugone** [comment]
@J-Ben87 what do you think ? did you ever used this feature ?

**Comment by J-Ben87** [comment]
Since Symfony 3.3 do the magic I guess it's not relevant to keep all this anymore

**Comment by yann-eugone** [comment]
I did registered all the things so the bundle comes with autoconfigure et autwire by default
