### ISSUE TITLE
Add add getChoiceLabel in AbstractTranslatedEnum

### ISSUE THREAD

**Issue by nicolas-bastien** [yann-eugone/enum-bundle#37]
Hi Yann,

In my project we need to get the translated choice in a list.

So in every actions, my new dev initialize an array with AbstractTranslatedEnum::getChoices and check if the value is set before displaying it.

Can we : 
- make an internal variable in AbstractTranslatedEnum to store the result so we do'nt have to walk through the array map each time the method is called
- and a getChoice method like 

```
public function getTranlatedChoice($value): string
{
    if(!this->hasChoice($value)) {
        return '';
     }

    return $this->getChoices()[$value];
}
```

I have Louis who will be more than happy to make it's first PR on a open source project.

What do you think about it ?

Nico

**Comment by yann-eugone** [comment]
Hey Nico :)

I'm not sure I understand why you need call `getChoices` by yourself.
Can't you use the built in twig filter ?

```
{{ value|enum_label('App\\Enum\\GenderEnum') }}
```

But your issue seems to be about performance, so you asked for caching choices in enum ?
I'm not against caching translated choices instead of translating "on the fly" any time `getChoices` is called.
But I'm pretty sure I will never introduce any public method on `AbstractTranslatedEnum`.

**Comment by nicolas-bastien** [comment]
Yes, we cannot use the twig extension because we do an API for VueJS Front.

Maybe you will reconsider your "never" because I know you like the thing simple like me.

![image](https://user-images.githubusercontent.com/1446466/117025696-6c610b00-acfb-11eb-9207-f8b7ea5753fb.png)


I think it's a good idea to have a getLabel method with the getChoices in AbstractTranslatedEnum and to use it too in your twig extension ?

If your ok, we will make a PR ?

**Comment by yann-eugone** [comment]
Ok, we could either add an intermediate service that the extension will use, but this is maybe overkill.

Ok for a `public function getLabel(string $value): string` method in enums, but it has to be part of the `EnumInterface`.

This will introduce breaking changes, so we will either have to find a way to softly handle this change, or move to a new major version with an upgrade note.

**Comment by yann-eugone** [comment]
@nicolas-bastien what do you think of #39 ?
Can you give it a try ?

**Comment by yann-eugone** [comment]
:rocket: [v3.3.0](https://github.com/yokai-php/enum-bundle/releases/tag/v3.3.0)
