### ISSUE TITLE
Return value of Yokai\EnumBundle\EnumRegistry::all() must be of the type array, null returned

### ISSUE THREAD

**Issue by Tentyfire** [yann-eugone/enum-bundle#55]
On using `EnumRegistry::all()` method when no Enums are created, the following error occurs :
```
Return value of Yokai\EnumBundle\EnumRegistry::all() must be of the type array, null returned
```

**Comment by yann-eugone** [comment]
Thank you for reporting this issue

This has been fixed in [`v4.0.3`](https://github.com/yokai-php/enum-bundle/releases/tag/v4.0.3)
